version: "3.9"

services:
  db:
    image: postgres:16
    container_name: db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./db/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER}"]
      interval: 10s
      timeout: 5s
      retries: 10

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    depends_on:
      db:
        condition: service_healthy
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://db:5432/${KEYCLOAK_DB}
      KC_DB_USERNAME: ${POSTGRES_USER}
      KC_DB_PASSWORD: ${POSTGRES_PASSWORD}
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
    volumes:
    - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-fsS", "http://localhost:8080/realms/master"]
      interval: 10s
      timeout: 5s
      retries: 10

  #api:
 #   build: ./api
 #   container_name: api
 #   depends_on:
 #     db:
 #       condition: service_healthy
 #     keycloak:
 #       condition: service_healthy
 #   environment:
 #     DB_HOST: db
 #     DB_PORT: 5432
 #     DB_USER: ${POSTGRES_USER}
 #     DB_PASSWORD: ${POSTGRES_PASSWORD}
 #     DB_NAME: ${RESTAURANT_DB}
 #     KEYCLOAK_URL: http://keycloak:8080
 #   ports:
 #     - "3000:3000"
 #   volumes:
 #     - ./api:/app

volumes:
  pgdata: