services:

  mongo1:
    image: mongo:7
    container_name: mongo1
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:7
    container_name: mongo2
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:7
    container_name: mongo3
    command: mongod --replSet rs0 --bind_ip_all
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db

  mongo-init:
    image: mongo:7
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    entrypoint: >
      bash -c "sleep 10 && mongosh --host mongo1 --eval '
        rs.initiate({
          _id: \"rs0\",
          members: [
            { _id: 0, host: \"mongo1:27017\" },
            { _id: 1, host: \"mongo2:27017\" },
            { _id: 2, host: \"mongo3:27017\" }
          ]
        })'
      "
    restart: on-failure

  keycloak:
    image: quay.io/keycloak/keycloak:24.0
    container_name: keycloak
    environment:
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KC_HTTP_ENABLED: true
      KC_IMPORT: /opt/keycloak/data/import/realm-export.json
      KC_HOSTNAME: localhost
      KC_HOSTNAME_PORT: 8080
      KC_HOSTNAME_STRICT: false
    volumes:
    - ./keycloak/realm-export.json:/opt/keycloak/data/import/realm-export.json
    command: ["start-dev", "--import-realm"]
    ports:
      - "8080:8080"


  redis:
    image: redis:7-alpine
    container_name: redis
    ports:
      - "6379:6379"
    command: >
      redis-server
      --maxmemory 256mb
      --maxmemory-policy allkeys-lru 
    volumes:
      # Persiste los datos de Redis aunque el contenedor se reinicie
      - redis_data:/data

    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  api:
    build: ./api
    container_name: api
    depends_on:
      keycloak:
        condition: service_started
      mongo1:
        condition: service_started
      mongo2:
        condition: service_started
      mongo3:
        condition: service_started
      redis:
        condition: service_healthy
    environment:
      DB_ENGINE: mongodb
      MONGO_URL: mongodb://mongo1:27017,mongo2:27017,mongo3:27017/?replicaSet=rs0
      MONGO_DB: restaurantdb
      KEYCLOAK_URL: http://keycloak:8080
      KEYCLOAK_PUBLIC_URL: http://localhost:8080 
      REALM: ${REALM}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
      KEYCLOAK_CLIENT_ID: ${KEYCLOAK_CLIENT_ID}         
      KEYCLOAK_CLIENT_SECRET: ${KEYCLOAK_CLIENT_SECRET} 
      KEYCLOAK_ADMIN_CLIENT_ID: ${KEYCLOAK_ADMIN_CLIENT_ID}
      REDIS_URL: redis://redis:6379
    ports:
      - "3000:3000"

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  redis_data: 