# redis/deployment.yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  namespace: restaurantes
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis
  namespace: restaurantes
  labels:
    app: redis
spec:
  replicas: 1   # Redis standalone — para HA usar Redis Sentinel o Cluster
  selector:
    matchLabels:
      app: redis
  template:
    metadata:
      labels:
        app: redis
    spec:
      containers:
        - name: redis
          image: redis:7-alpine
          command:
            - redis-server
            - "--maxmemory"
            - "256mb"
            - "--maxmemory-policy"
            - "allkeys-lru"
            - "--save"
            - "60 1"       # Persistencia: guarda si hay ≥1 cambio en 60s
          ports:
            - containerPort: 6379
          volumeMounts:
            - name: redis-data
              mountPath: /data
          readinessProbe:
            exec:
              command: ["redis-cli", "ping"]
            initialDelaySeconds: 5
            periodSeconds: 5
          resources:
            requests:
              cpu:    "50m"
              memory: "128Mi"
            limits:
              cpu:    "200m"
              memory: "320Mi"
      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: redis-service
  namespace: restaurantes
spec:
  selector:
    app: redis
  ports:
    - protocol: TCP
      port:       6379
      targetPort: 6379
  type: ClusterIP