# postgres/statefulset.yaml
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres
  namespace: restaurantes
  labels:
    app: postgres
spec:
  serviceName: postgres-service
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          env:
            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: restaurantes-secrets
                  key:  DB_USER
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: restaurantes-secrets
                  key:  DB_PASSWORD
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: restaurantes-config
                  key:  DB_NAME
          ports:
            - containerPort: 5432
          volumeMounts:
            - name: pg-data
              mountPath: /var/lib/postgresql/data
            # Monta los scripts SQL de inicialización
            - name: init-scripts
              mountPath: /docker-entrypoint-initdb.d
          readinessProbe:
            exec:
              command:
                - pg_isready
                - "-U"
                - "$(POSTGRES_USER)"
                - "-d"
                - "$(POSTGRES_DB)"
            initialDelaySeconds: 10
            periodSeconds: 5
          resources:
            requests:
              cpu:    "100m"
              memory: "256Mi"
            limits:
              cpu:    "500m"
              memory: "512Mi"
      volumes:
        - name: init-scripts
          configMap:
            name: postgres-init-scripts   # Ver postgres/init-configmap.yaml
  volumeClaimTemplates:
    - metadata:
        name: pg-data
      spec:
        accessModes: ["ReadWriteOnce"]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-service
  namespace: restaurantes
spec:
  selector:
    app: postgres
  ports:
    - protocol: TCP
      port:       5432
      targetPort: 5432
  type: ClusterIP