# Imagen de Node
FROM node:20-alpine

# Carpeta de trabajo
WORKDIR /app

# Copiar package.json 
COPY package*.json ./

# Instalar dependencias
RUN npm install

# Copiar el resto del código
COPY . .

# Poner solo las variables de entorno necesarias para la aplicación
# ENV PORT 
# ENV POSTGRES_DB_HOST

# Exponer el puerto
EXPOSE 3000

# Comando para iniciar la aplicación
CMD ["node", "src/app.js"]